services:
  regpac:
    image: ghcr.io/eraby-fr/regpac:0.0.13
    container_name: regpac_container
    volumes:
      - ./config:/container/config/
    ports:
      - "7654:7654"
    restart: unless-stopped
    network_mode: "host"
  regpac-webdashboard:
    image: ghcr.io/eraby-fr/regpac-webdashboard:latest
    container_name: regpac_webdashboard_container
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - regpac
  telegraf:
    image: telegraf:1.33.1
    restart: always
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /tmp/fhem_logs/:/tmp/fhem_logs/
    network_mode: "host"
  grafana:
    image: grafana/grafana-arm32v7-linux:7.0.6
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=kern0
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/grafana-provisioning/:/etc/grafana/provisioning
    network_mode: "host"
volumes:
  grafana-storage:
